# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["bcunningham@fastly.com"]
description = "api to host pwned password data from haveibeenpwned.com"
language = "rust"
manifest_version = 2
name = "compute-hibp-passwords-api"
service_id = ""

[local_server]

  [local_server.backends]

  [local_server.object_store]

    [[local_server.object_store.hibp-store]]
      key = "00000"
      path = "hibp_object_store/00000.txt"

    [[local_server.object_store.hibp-store]]
      key = "00001"
      path = "hibp_object_store/00001.txt"

    [[local_server.object_store.hibp-store]]
      key = "00002"
      path = "hibp_object_store/00002.txt"

[scripts]
  build = "cargo build --bin fastly-compute-project --release --target wasm32-wasi --color always"
